// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjdcjdnaiinmpnhfuhhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZGNqZG5haWlubXBuaGZ1aGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTMxNDgsImV4cCI6MjA2NzUyOTE0OH0.fJ-QLW5x5w1Udd9KrZoDmZcuaeAipzed9-5dWqPKxKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});